<?php

namespace AppBundle\Repository;

/**
 * SignaletiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignaletiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
